### ISSUE TITLE
Build fails with mink-idl-compiler >= 0.3.0: `Object_OP_version` undeclared

### ISSUE THREAD

**Issue by aekoroglu** [qualcomm/minkipc#89]
minkipc does not build with any `idlc` from v0.3.0  onward, because `libminkadaptor/include/object.h` does not define `Object_OP_version`.

## Reproducing

Build with idlc 1.0.1 (current release):

```
cmake .. -DMINKIDLC_BIN_DIR=/usr/bin
cmake --build .
```

Every generated header fails to compile:

```
libminkteec/idl/IGPSession.h: In function 'IGPSession_api_version':
libminkteec/idl/IGPSession.h:53:32: error: 'Object_OP_version' undeclared
   (first use in this function); did you mean 'Object_OP_retain'?
   53 |     return Object_invoke(self, Object_OP_version, a, ObjectCounts_pack(0, 1, 0, 0));
```

and in the `--skel` output, inside the generated dispatch macro:

```
IListenerCBO_invoke.h:31:18: error: 'Object_OP_version' undeclared
   31 |             case Object_OP_version: { \
```

## Cause

mink-idl-compiler v0.3.0 added interface versioning. From that release onward, every generated interface gets an `I<Interface>_api_version()` helper and a matching `case Object_OP_version:` arm in the `I<Interface>_DEFINE_INVOKE` skeleton macro.

The same release updated the compiler's reference `object.h` (`tests/c/object.h`), which defines:

```c
#define Object_OP_version (ObjectOp_LOCAL - 1)
```

minkipc's `libminkadaptor/include/object.h` defines only `Object_OP_release` and `Object_OP_retain`. This is still the case on `main`.

## Suggested fix

Add to `libminkadaptor/include/object.h`:

```c
#define Object_OP_version (ObjectOp_LOCAL - 1)
```

The value derives from `ObjectOp_LOCAL` rather than `ObjectOp_METHOD_MASK`, placing it in the reserved range alongside release/retain, so it does not affect positional method op codes.

It would also help to state the supported `idlc` version range in the README, so a mismatch is detectable before it becomes a build error.
